title: Standardseite

status:
  draft: true
  unlisted:
    label: Versteckte Seite
    text: Die Seite taucht nicht in der Hauptnavigation auf
  listed:
    label: Menüseite
    text: Die Seite hat einen Eintrag in der Hauptnavigation

columns:
  - width: 3/4
    fields:
      layout:
        extends: fields/layout
  - width: 1/4
    sections:
      fields:
        type: fields
        fields:
          size:
            label: Seitenbreite
            type: select
            default: default
            required: true
            options:
              default: Standard
              small: Schmal
      files:
        label: Dateien
        type: files
        batch: true
