# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.

# The site blueprint usually provides easy access to all main pages of the site.
# In this example blueprint, we also show subpages of the `photography` and `notes` pages.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site


tabs:
  pages:
    label: Pages
    icon: page
    columns:
      main:
        width: 1/2
        sections:
          angebote: sections/angebote
      sidebar:
        width: 1/2
        sections:
          pages:
            label: Seiten
            type: pages
            templates: [default, text]
          specialpages:
            label: Spezialseiten
            type: pages
            templatesIgnore:
              - default
              - text
              - angebot


  meta:
    label: Meta
    icon: info
    columns:
      - width: 1/2
        sections:
          footer:
            type: fields
            fields:
              footertext:
                type: writer
              sponsors:
                type: structure
                fields:
                  name:
                    label: Name
                    type: text
                    required: true
                  logo:
                    extends: fields/image
                    required: true
                  link:
                    label: Link
                    type: url
              footerlinks:
                type: structure
                fields:
                  label:
                    label: Label
                    type: text
                    required: true
                  url:
                    label: URL
                    type: link
                    required: true
      - width: 1/2
        sections:
          seo:
            type: fields
            fields:
              seodescription:
                label: Kurzbeschreibung für Suchmaschinen
                type: text
                help: Diesen Text verwendet z.B. Google für die Zusammenfassung in den Suchergebnissen
                spellcheck: true

